#pragma checksum "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "C4E2D3983213E59DD9B2BB2E04BD25C4E9807E2B"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



public partial class Page_SM200522 : System.Web.SessionState.IRequiresSessionState {
    
    
    #line 7 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
    protected global::PX.Web.UI.PXDataSource ds;
    
    #line default
    #line hidden
    
    
    #line 22 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
    protected global::PX.Web.UI.PXTextEdit edTitle;
    
    #line default
    #line hidden
    
    
    #line 23 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
    protected global::PX.Web.UI.PXTextEdit edUrl;
    
    #line default
    #line hidden
    
    
    #line 24 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
    protected global::PX.Web.UI.PXTextEdit edGraphtype;
    
    #line default
    #line hidden
    
    
    #line 25 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
    protected global::PX.Web.UI.PXMaskEdit edScreenID;
    
    #line default
    #line hidden
    
    
    #line 26 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
    protected global::PX.Web.UI.PXDropDown edWorkspaces;
    
    #line default
    #line hidden
    
    
    #line 27 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
    protected global::PX.Web.UI.PXDropDown edCategory;
    
    #line default
    #line hidden
    
    
    #line 28 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
    protected global::PX.Web.UI.PXCheckBox chkLEP;
    
    #line default
    #line hidden
    
    
    #line 14 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
    protected global::PX.Web.UI.PXGrid grid;
    
    #line default
    #line hidden
    
    protected System.Web.Profile.DefaultProfile Profile {
        get {
            return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
        }
    }
    
    protected ASP.global_asax ApplicationInstance {
        get {
            return ((ASP.global_asax)(this.Context.ApplicationInstance));
        }
    }
    
    public new ASP.masterpages_listview_master Master {
        get {
            return ((ASP.masterpages_listview_master)(base.Master));
        }
    }
}
namespace ASP {
    
    #line 6 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
    using System.Web.UI.WebControls.Expressions;
    
    #line default
    #line hidden
    
    #line 337 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.Security;
    
    #line default
    #line hidden
    
    #line 325 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 331 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Text;
    
    #line default
    #line hidden
    
    #line 6 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
    using System.Web.UI;
    
    #line default
    #line hidden
    
    #line 326 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 330 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Linq;
    
    #line default
    #line hidden
    
    #line 5 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
    using ASP;
    
    #line default
    #line hidden
    
    #line 336 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.SessionState;
    
    #line default
    #line hidden
    
    #line 329 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Configuration;
    
    #line default
    #line hidden
    
    #line 333 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web;
    
    #line default
    #line hidden
    
    #line 6 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
    using System.Web.DynamicData;
    
    #line default
    #line hidden
    
    #line 334 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.Caching;
    
    #line default
    #line hidden
    
    #line 338 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.Profile;
    
    #line default
    #line hidden
    
    #line 328 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.ComponentModel.DataAnnotations;
    
    #line default
    #line hidden
    
    #line 327 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Collections.Specialized;
    
    #line default
    #line hidden
    
    #line 6 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
    using System.Web.UI.WebControls;
    
    #line default
    #line hidden
    
    #line 324 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System;
    
    #line default
    #line hidden
    
    #line 6 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
    using System.Web.UI.WebControls.WebParts;
    
    #line default
    #line hidden
    
    #line 332 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    
    #line 6 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
    using System.Web.UI.DataVisualization.Charting;
    
    #line default
    #line hidden
    
    #line 7 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
    using PX.Web.UI;
    
    #line default
    #line hidden
    
    #line 343 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Xml.Linq;
    
    #line default
    #line hidden
    
    #line 342 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.UI.HtmlControls;
    
    #line default
    #line hidden
    
    
    [System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
    public class pages_sm_sm200522_aspx : global::Page_SM200522, System.Web.IHttpHandler {
        
        private static System.Reflection.MethodInfo @__PageInspector_SetTraceDataMethod = global::ASP.pages_sm_sm200522_aspx.@__PageInspector_LoadHelper("SetTraceData");
        
        private static bool @__initialized;
        
        private static object @__fileDependencies;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public pages_sm_sm200522_aspx() {
            string[] dependencies;
            
            #line 912304 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx.cs"
            ((global::System.Web.UI.Page)(this)).AppRelativeVirtualPath = "~/Pages/SM/SM200522.aspx";
            
            #line default
            #line hidden
            if ((global::ASP.pages_sm_sm200522_aspx.@__initialized == false)) {
                dependencies = new string[6];
                dependencies[0] = "~/Pages/SM/SM200522.aspx";
                dependencies[1] = "~/Controls/PageTitle.ascx";
                dependencies[2] = "~/Controls/PageTitle.ascx.cs";
                dependencies[3] = "~/MasterPages/ListView.master";
                dependencies[4] = "~/MasterPages/ListView.master.cs";
                dependencies[5] = "~/Pages/SM/SM200522.aspx.cs";
                global::ASP.pages_sm_sm200522_aspx.@__fileDependencies = this.GetWrappedFileDependencies(dependencies);
                global::ASP.pages_sm_sm200522_aspx.@__initialized = true;
            }
            this.Server.ScriptTimeout = 30000000;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control2() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\n\t");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        340,
                        2,
                        true});
            return @__ctrl;
        }
        
        private static System.Reflection.MethodInfo @__PageInspector_LoadHelper(string helperName) {
            System.Type helperClass = System.Type.GetType("Microsoft.WebTools.BrowserLink.Runtime.WebForms.TraceHelpers, Microsoft.WebTools." +
                    "BrowserLink.Tracing, Version=16.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f1" +
                    "1d50a3a", false, false);
            if ((helperClass != null)) {
                return helperClass.GetMethod(helperName);
            }
            return null;
        }
        
        private void @__PageInspector_SetTraceData(object[] parameters) {
            if ((global::ASP.pages_sm_sm200522_aspx.@__PageInspector_SetTraceDataMethod != null)) {
                global::ASP.pages_sm_sm200522_aspx.@__PageInspector_SetTraceDataMethod.Invoke(null, parameters);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::PX.Web.UI.PXDataSource @__BuildControlds() {
            global::PX.Web.UI.PXDataSource @__ctrl;
            
            #line 7 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl = new global::PX.Web.UI.PXDataSource();
            
            #line default
            #line hidden
            this.ds = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 7 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl.ID = "ds";
            
            #line default
            #line hidden
            
            #line 7 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(100D, global::System.Web.UI.WebControls.UnitType.Percentage);
            
            #line default
            #line hidden
            
            #line 7 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl.PrimaryView = "SiteMap";
            
            #line default
            #line hidden
            
            #line 7 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl.TypeName = "PX.SiteMap.Graph.PortalISVMapMaint";
            
            #line default
            #line hidden
            
            #line 7 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl.Visible = true;
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        342,
                        200,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control3() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\n");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        542,
                        1,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlcont1(System.Web.UI.Control @__ctrl) {
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 6 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl1 = this.@__BuildControl__control2();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 6 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::PX.Web.UI.PXDataSource @__ctrl2;
            
            #line 6 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl2 = this.@__BuildControlds();
            
            #line default
            #line hidden
            
            #line 6 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl3;
            
            #line 6 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl3 = this.@__BuildControl__control3();
            
            #line default
            #line hidden
            
            #line 6 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control4() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\n\t");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        624,
                        2,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control8() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\n\t\t\t\t    ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        899,
                        9,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::PX.Web.UI.PXLayoutRule @__BuildControl__control9() {
            global::PX.Web.UI.PXLayoutRule @__ctrl;
            
            #line 20 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl = new global::PX.Web.UI.PXLayoutRule();
            
            #line default
            #line hidden
            @__ctrl.TemplateControl = this;
            
            #line 20 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl.StartColumn = true;
            
            #line default
            #line hidden
            
            #line 20 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl.LabelsWidth = "M";
            
            #line default
            #line hidden
            
            #line 20 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl.ControlSize = "L";
            
            #line default
            #line hidden
            
            #line 20 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl.StartGroup = true;
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        908,
                        130,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control10() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\n\t\t\t\t    ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1038,
                        9,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::PX.Web.UI.PXTextEdit @__BuildControledTitle() {
            global::PX.Web.UI.PXTextEdit @__ctrl;
            
            #line 22 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl = new global::PX.Web.UI.PXTextEdit();
            
            #line default
            #line hidden
            this.edTitle = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 22 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl.ID = "edTitle";
            
            #line default
            #line hidden
            
            #line 22 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl.DataField = "Title";
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1047,
                        79,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control11() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\n\t\t\t\t    ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1126,
                        9,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::PX.Web.UI.PXTextEdit @__BuildControledUrl() {
            global::PX.Web.UI.PXTextEdit @__ctrl;
            
            #line 23 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl = new global::PX.Web.UI.PXTextEdit();
            
            #line default
            #line hidden
            this.edUrl = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 23 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl.ID = "edUrl";
            
            #line default
            #line hidden
            
            #line 23 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl.DataField = "Url";
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1135,
                        75,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control12() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\n\t\t\t\t    ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1210,
                        9,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::PX.Web.UI.PXTextEdit @__BuildControledGraphtype() {
            global::PX.Web.UI.PXTextEdit @__ctrl;
            
            #line 24 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl = new global::PX.Web.UI.PXTextEdit();
            
            #line default
            #line hidden
            this.edGraphtype = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 24 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl.ID = "edGraphtype";
            
            #line default
            #line hidden
            
            #line 24 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl.DataField = "Graphtype";
            
            #line default
            #line hidden
            
            #line 24 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl.Enabled = false;
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1219,
                        103,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control13() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\n\t\t\t\t    ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1322,
                        9,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::PX.Web.UI.PXMaskEdit @__BuildControledScreenID() {
            global::PX.Web.UI.PXMaskEdit @__ctrl;
            
            #line 25 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl = new global::PX.Web.UI.PXMaskEdit();
            
            #line default
            #line hidden
            this.edScreenID = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 25 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl.ID = "edScreenID";
            
            #line default
            #line hidden
            
            #line 25 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl.DataField = "ScreenID";
            
            #line default
            #line hidden
            
            #line 25 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl.InputMask = "CC.CC.CC.CC";
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1331,
                        109,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control14() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\n\t\t\t\t    ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1440,
                        9,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::PX.Web.UI.PXDropDown @__BuildControledWorkspaces() {
            global::PX.Web.UI.PXDropDown @__ctrl;
            
            #line 26 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl = new global::PX.Web.UI.PXDropDown();
            
            #line default
            #line hidden
            this.edWorkspaces = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 26 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl.ID = "edWorkspaces";
            
            #line default
            #line hidden
            
            #line 26 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl.DataField = "Workspaces";
            
            #line default
            #line hidden
            
            #line 26 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl.AllowMultiSelect = true;
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1449,
                        96,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control15() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\n\t\t\t\t    ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1545,
                        9,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::PX.Web.UI.PXDropDown @__BuildControledCategory() {
            global::PX.Web.UI.PXDropDown @__ctrl;
            
            #line 27 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl = new global::PX.Web.UI.PXDropDown();
            
            #line default
            #line hidden
            this.edCategory = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 27 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl.ID = "edCategory";
            
            #line default
            #line hidden
            
            #line 27 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl.DataField = "Category";
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1554,
                        68,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control16() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\n\t\t\t\t    ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1622,
                        9,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::PX.Web.UI.PXCheckBox @__BuildControlchkLEP() {
            global::PX.Web.UI.PXCheckBox @__ctrl;
            
            #line 28 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl = new global::PX.Web.UI.PXCheckBox();
            
            #line default
            #line hidden
            this.chkLEP = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 28 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl.ID = "chkLEP";
            
            #line default
            #line hidden
            
            #line 28 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl.DataField = "ListIsEntryPoint";
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1631,
                        72,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control17() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\n\t\t\t\t");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1703,
                        5,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control7(System.Web.UI.Control @__ctrl) {
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 18 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl1 = this.@__BuildControl__control8();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 18 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::PX.Web.UI.PXLayoutRule @__ctrl2;
            
            #line 18 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl2 = this.@__BuildControl__control9();
            
            #line default
            #line hidden
            
            #line 18 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl3;
            
            #line 18 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl3 = this.@__BuildControl__control10();
            
            #line default
            #line hidden
            
            #line 18 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            global::PX.Web.UI.PXTextEdit @__ctrl4;
            
            #line 18 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl4 = this.@__BuildControledTitle();
            
            #line default
            #line hidden
            
            #line 18 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl5;
            
            #line 18 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl5 = this.@__BuildControl__control11();
            
            #line default
            #line hidden
            
            #line 18 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
            global::PX.Web.UI.PXTextEdit @__ctrl6;
            
            #line 18 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl6 = this.@__BuildControledUrl();
            
            #line default
            #line hidden
            
            #line 18 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__parser.AddParsedSubObject(@__ctrl6);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl7;
            
            #line 18 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl7 = this.@__BuildControl__control12();
            
            #line default
            #line hidden
            
            #line 18 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__parser.AddParsedSubObject(@__ctrl7);
            
            #line default
            #line hidden
            global::PX.Web.UI.PXTextEdit @__ctrl8;
            
            #line 18 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl8 = this.@__BuildControledGraphtype();
            
            #line default
            #line hidden
            
            #line 18 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__parser.AddParsedSubObject(@__ctrl8);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl9;
            
            #line 18 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl9 = this.@__BuildControl__control13();
            
            #line default
            #line hidden
            
            #line 18 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__parser.AddParsedSubObject(@__ctrl9);
            
            #line default
            #line hidden
            global::PX.Web.UI.PXMaskEdit @__ctrl10;
            
            #line 18 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl10 = this.@__BuildControledScreenID();
            
            #line default
            #line hidden
            
            #line 18 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__parser.AddParsedSubObject(@__ctrl10);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl11;
            
            #line 18 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl11 = this.@__BuildControl__control14();
            
            #line default
            #line hidden
            
            #line 18 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__parser.AddParsedSubObject(@__ctrl11);
            
            #line default
            #line hidden
            global::PX.Web.UI.PXDropDown @__ctrl12;
            
            #line 18 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl12 = this.@__BuildControledWorkspaces();
            
            #line default
            #line hidden
            
            #line 18 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__parser.AddParsedSubObject(@__ctrl12);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl13;
            
            #line 18 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl13 = this.@__BuildControl__control15();
            
            #line default
            #line hidden
            
            #line 18 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__parser.AddParsedSubObject(@__ctrl13);
            
            #line default
            #line hidden
            global::PX.Web.UI.PXDropDown @__ctrl14;
            
            #line 18 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl14 = this.@__BuildControledCategory();
            
            #line default
            #line hidden
            
            #line 18 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__parser.AddParsedSubObject(@__ctrl14);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl15;
            
            #line 18 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl15 = this.@__BuildControl__control16();
            
            #line default
            #line hidden
            
            #line 18 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__parser.AddParsedSubObject(@__ctrl15);
            
            #line default
            #line hidden
            global::PX.Web.UI.PXCheckBox @__ctrl16;
            
            #line 18 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl16 = this.@__BuildControlchkLEP();
            
            #line default
            #line hidden
            
            #line 18 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__parser.AddParsedSubObject(@__ctrl16);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl17;
            
            #line 18 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl17 = this.@__BuildControl__control17();
            
            #line default
            #line hidden
            
            #line 18 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__parser.AddParsedSubObject(@__ctrl17);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::PX.Web.UI.PXGridColumn @__BuildControl__control19() {
            global::PX.Web.UI.PXGridColumn @__ctrl;
            
            #line 31 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl = new global::PX.Web.UI.PXGridColumn();
            
            #line default
            #line hidden
            
            #line 31 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl.DataField = "ScreenID";
            
            #line default
            #line hidden
            
            #line 31 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl.DisplayFormat = "CC.CC.CC.CC";
            
            #line default
            #line hidden
            
            #line 31 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl.CommitChanges = true;
            
            #line default
            #line hidden
            
            #line 31 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(120D, global::System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::PX.Web.UI.PXGridColumn @__BuildControl__control20() {
            global::PX.Web.UI.PXGridColumn @__ctrl;
            
            #line 32 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl = new global::PX.Web.UI.PXGridColumn();
            
            #line default
            #line hidden
            
            #line 32 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl.DataField = "Title";
            
            #line default
            #line hidden
            
            #line 32 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(200D, global::System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::PX.Web.UI.PXGridColumn @__BuildControl__control21() {
            global::PX.Web.UI.PXGridColumn @__ctrl;
            
            #line 33 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl = new global::PX.Web.UI.PXGridColumn();
            
            #line default
            #line hidden
            
            #line 33 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl.DataField = "Url";
            
            #line default
            #line hidden
            
            #line 33 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(200D, global::System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            
            #line 33 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl.CommitChanges = true;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::PX.Web.UI.PXGridColumn @__BuildControl__control22() {
            global::PX.Web.UI.PXGridColumn @__ctrl;
            
            #line 34 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl = new global::PX.Web.UI.PXGridColumn();
            
            #line default
            #line hidden
            
            #line 34 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl.DataField = "Graphtype";
            
            #line default
            #line hidden
            
            #line 34 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(200D, global::System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::PX.Web.UI.PXGridColumn @__BuildControl__control23() {
            global::PX.Web.UI.PXGridColumn @__ctrl;
            
            #line 35 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl = new global::PX.Web.UI.PXGridColumn();
            
            #line default
            #line hidden
            
            #line 35 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl.DataField = "Workspaces";
            
            #line default
            #line hidden
            
            #line 35 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(200D, global::System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::PX.Web.UI.PXGridColumn @__BuildControl__control24() {
            global::PX.Web.UI.PXGridColumn @__ctrl;
            
            #line 36 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl = new global::PX.Web.UI.PXGridColumn();
            
            #line default
            #line hidden
            
            #line 36 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl.DataField = "Category";
            
            #line default
            #line hidden
            
            #line 36 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(200D, global::System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::PX.Web.UI.PXGridColumn @__BuildControl__control25() {
            global::PX.Web.UI.PXGridColumn @__ctrl;
            
            #line 37 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl = new global::PX.Web.UI.PXGridColumn();
            
            #line default
            #line hidden
            
            #line 37 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl.DataField = "ListIsEntryPoint";
            
            #line default
            #line hidden
            
            #line 37 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl.TextAlign = global::System.Web.UI.WebControls.HorizontalAlign.Center;
            
            #line default
            #line hidden
            
            #line 37 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl.Type = global::PX.Web.UI.GridColumnType.CheckBox;
            
            #line default
            #line hidden
            
            #line 37 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(60D, global::System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control18(PX.Web.UI.PXGridColumnCollection @__ctrl) {
            global::PX.Web.UI.PXGridColumn @__ctrl1;
            
            #line 18 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl1 = this.@__BuildControl__control19();
            
            #line default
            #line hidden
            
            #line 18 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl.Add(@__ctrl1);
            
            #line default
            #line hidden
            global::PX.Web.UI.PXGridColumn @__ctrl2;
            
            #line 18 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl2 = this.@__BuildControl__control20();
            
            #line default
            #line hidden
            
            #line 18 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl.Add(@__ctrl2);
            
            #line default
            #line hidden
            global::PX.Web.UI.PXGridColumn @__ctrl3;
            
            #line 18 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl3 = this.@__BuildControl__control21();
            
            #line default
            #line hidden
            
            #line 18 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl.Add(@__ctrl3);
            
            #line default
            #line hidden
            global::PX.Web.UI.PXGridColumn @__ctrl4;
            
            #line 18 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl4 = this.@__BuildControl__control22();
            
            #line default
            #line hidden
            
            #line 18 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl.Add(@__ctrl4);
            
            #line default
            #line hidden
            global::PX.Web.UI.PXGridColumn @__ctrl5;
            
            #line 18 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl5 = this.@__BuildControl__control23();
            
            #line default
            #line hidden
            
            #line 18 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl.Add(@__ctrl5);
            
            #line default
            #line hidden
            global::PX.Web.UI.PXGridColumn @__ctrl6;
            
            #line 18 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl6 = this.@__BuildControl__control24();
            
            #line default
            #line hidden
            
            #line 18 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl.Add(@__ctrl6);
            
            #line default
            #line hidden
            global::PX.Web.UI.PXGridColumn @__ctrl7;
            
            #line 18 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl7 = this.@__BuildControl__control25();
            
            #line default
            #line hidden
            
            #line 18 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl.Add(@__ctrl7);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control27(PX.Web.UI.PXStyle @__ctrl) {
            
            #line 18 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl.Height = new System.Web.UI.WebControls.Unit(250D, global::System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control26(PX.Web.UI.PXGridLevelStyles @__ctrl) {
            
            #line 18 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            this.@__BuildControl__control27(@__ctrl.RowForm);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::PX.Web.UI.PXGridLevel @__BuildControl__control6() {
            global::PX.Web.UI.PXGridLevel @__ctrl;
            
            #line 18 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl = new global::PX.Web.UI.PXGridLevel();
            
            #line default
            #line hidden
            
            #line 18 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl.RowTemplate = new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control7));
            
            #line default
            #line hidden
            
            #line 18 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl.DataMember = "SiteMap";
            
            #line default
            #line hidden
            
            #line 18 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            this.@__BuildControl__control18(@__ctrl.Columns);
            
            #line default
            #line hidden
            
            #line 18 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            this.@__BuildControl__control26(@__ctrl.Styles);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control5(PX.Web.UI.PXGridLevelCollection @__ctrl) {
            global::PX.Web.UI.PXGridLevel @__ctrl1;
            
            #line 14 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl1 = this.@__BuildControl__control6();
            
            #line default
            #line hidden
            
            #line 14 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl.Add(@__ctrl1);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control28(PX.Web.UI.PXGridLevelLayout @__ctrl) {
            
            #line 14 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl.FormViewHeight = new System.Web.UI.WebControls.Unit(250D, global::System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control29(PX.Web.UI.PXAutoSizeInfo @__ctrl) {
            
            #line 14 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl.Container = global::PX.Web.UI.DockContainer.Window;
            
            #line default
            #line hidden
            
            #line 14 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl.Enabled = true;
            
            #line default
            #line hidden
            
            #line 14 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl.MinHeight = 200;
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control30(PX.Web.UI.PXGridLevelMode @__ctrl) {
            
            #line 14 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl.AllowUpload = new System.Nullable<bool>(true);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control32(PX.Web.UI.PXCallbackCommand @__ctrl) {
            
            #line 14 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl.PostData = global::PX.Web.UI.PostDataMode.Content;
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control31(PX.Web.UI.PXGridCallbacks @__ctrl) {
            
            #line 14 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            this.@__BuildControl__control32(@__ctrl.Save);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::PX.Web.UI.PXGrid @__BuildControlgrid() {
            global::PX.Web.UI.PXGrid @__ctrl;
            
            #line 14 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl = new global::PX.Web.UI.PXGrid();
            
            #line default
            #line hidden
            this.grid = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.SkinID = "Primary";
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 14 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl.ID = "grid";
            
            #line default
            #line hidden
            
            #line 14 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl.Height = new System.Web.UI.WebControls.Unit(350D, global::System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            
            #line 14 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(100D, global::System.Web.UI.WebControls.UnitType.Percentage);
            
            #line default
            #line hidden
            
            #line 14 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl.AdjustPageSize = global::PX.Web.UI.GridPageSizeMode.Auto;
            
            #line default
            #line hidden
            
            #line 14 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl.AllowPaging = true;
            
            #line default
            #line hidden
            
            #line 14 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl.AllowSearch = true;
            
            #line default
            #line hidden
            
            #line 14 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl.FastFilterFields = new string[] {
                    "ScreenID",
                    "Title"};
            
            #line default
            #line hidden
            
            #line 14 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl.SyncPosition = true;
            
            #line default
            #line hidden
            
            #line 14 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            this.@__BuildControl__control5(@__ctrl.Levels);
            
            #line default
            #line hidden
            
            #line 14 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            this.@__BuildControl__control28(@__ctrl.Layout);
            
            #line default
            #line hidden
            
            #line 14 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            this.@__BuildControl__control29(@__ctrl.AutoSize);
            
            #line default
            #line hidden
            
            #line 14 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            this.@__BuildControl__control30(@__ctrl.Mode);
            
            #line default
            #line hidden
            
            #line 14 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            this.@__BuildControl__control31(@__ctrl.CallbackCommands);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        626,
                        2050,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control33() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\n");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2676,
                        1,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlcont(System.Web.UI.Control @__ctrl) {
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 13 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl1 = this.@__BuildControl__control4();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 13 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::PX.Web.UI.PXGrid @__ctrl2;
            
            #line 13 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl2 = this.@__BuildControlgrid();
            
            #line default
            #line hidden
            
            #line 13 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl3;
            
            #line 13 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl3 = this.@__BuildControl__control33();
            
            #line default
            #line hidden
            
            #line 13 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlTree(pages_sm_sm200522_aspx @__ctrl) {
            
            #line 1 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl.MasterPageFile = "~/MasterPages/ListView.master";
            
            #line default
            #line hidden
            
            #line 1 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__ctrl.Title = "ISV Portal Map Maintenance";
            
            #line default
            #line hidden
            
            #line 1 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            this.InitializeCulture();
            
            #line default
            #line hidden
            
            #line 6 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            this.AddContentTemplate("phDS", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControlcont1)));
            
            #line default
            #line hidden
            
            #line 13 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            this.AddContentTemplate("phL", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControlcont)));
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\n\n"));
            
            #line default
            #line hidden
            
            #line 1 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            
            #line default
            #line hidden
        }
        
        
        #line 912304 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Pages\SM\SM200522.aspx.cs"
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void FrameworkInitialize() {
            this.StyleSheetTheme = "Default";
            base.FrameworkInitialize();
            this.@__BuildControlTree(this);
            this.AddWrappedFileDependencies(global::ASP.pages_sm_sm200522_aspx.@__fileDependencies);
            this.ValidateRequestMode = System.Web.UI.ValidateRequestMode.Disabled;
        }
        
        #line default
        #line hidden
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override int GetTypeHashCode() {
            return -1031465456;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override void ProcessRequest(System.Web.HttpContext context) {
            base.ProcessRequest(context);
        }
    }
}
