//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.CodeDom.Compiler.GeneratedCodeAttribute("ASP.NET", "4.0.30319.42000")]
[assembly: System.Security.SecurityRulesAttribute(System.Security.SecurityRuleSet.Level2)]
[assembly: System.Runtime.Versioning.TargetFrameworkAttribute(".NETFramework,Version=v4.8")]

namespace @__ASP {
    
    
    internal class FastObjectFactory_app_web_p15e425g {
        
        
        #line 1 "c:\\dummy.txt"

        #line default
        #line hidden
        
        
        private FastObjectFactory_app_web_p15e425g() {
        }
        
        static object Create_ASP_pages_sm_sm501000_aspx() {
            return new ASP.pages_sm_sm501000_aspx();
        }
        
        static object Create_ASP_pages_sm_sm301010_aspx() {
            return new ASP.pages_sm_sm301010_aspx();
        }
        
        static object Create_ASP_pages_sm_sm200523_aspx() {
            return new ASP.pages_sm_sm200523_aspx();
        }
        
        static object Create_ASP_pages_sm_sm206505_aspx() {
            return new ASP.pages_sm_sm206505_aspx();
        }
        
        static object Create_ASP_pages_sm_sm202065_aspx() {
            return new ASP.pages_sm_sm202065_aspx();
        }
        
        static object Create_ASP_pages_sm_sm208020_aspx() {
            return new ASP.pages_sm_sm208020_aspx();
        }
        
        static object Create_ASP_pages_sm_sm204540_aspx() {
            return new ASP.pages_sm_sm204540_aspx();
        }
        
        static object Create_ASP_pages_sm_sm204003_aspx() {
            return new ASP.pages_sm_sm204003_aspx();
        }
        
        static object Create_ASP_pages_sm_sm200529_aspx() {
            return new ASP.pages_sm_sm200529_aspx();
        }
        
        static object Create_ASP_pages_sm_sm201045_aspx() {
            return new ASP.pages_sm_sm201045_aspx();
        }
        
        static object Create_ASP_pages_sm_sm511500_aspx() {
            return new ASP.pages_sm_sm511500_aspx();
        }
    }
}
