#pragma checksum "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "2E6391EC92A642A3D6A674190D649B1CF86D04BD"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



public partial class Api_Menu : System.Web.SessionState.IRequiresSessionState {
    
    
    #line 41 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
    protected global::System.Web.UI.WebControls.Button ButtonClearTrace;
    
    #line default
    #line hidden
    
    
    #line 44 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
    protected global::System.Web.UI.WebControls.Button ButtonClearCaches;
    
    #line default
    #line hidden
    
    
    #line 47 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
    protected global::System.Web.UI.WebControls.CheckBox CheckPaused;
    
    #line default
    #line hidden
    
    
    #line 49 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
    protected global::System.Web.UI.WebControls.Label Label1;
    
    #line default
    #line hidden
    
    
    #line 38 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
    protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    
    #line default
    #line hidden
    
    protected System.Web.Profile.DefaultProfile Profile {
        get {
            return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
        }
    }
    
    protected ASP.global_asax ApplicationInstance {
        get {
            return ((ASP.global_asax)(this.Context.ApplicationInstance));
        }
    }
}
namespace ASP {
    
    #line 25 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
    using System.Web.UI.DataVisualization.Charting;
    
    #line default
    #line hidden
    
    #line 330 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Linq;
    
    #line default
    #line hidden
    
    #line 337 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.Security;
    
    #line default
    #line hidden
    
    #line 326 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 332 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    
    #line 25 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
    using System.Web.UI.WebControls;
    
    #line default
    #line hidden
    
    #line 343 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Xml.Linq;
    
    #line default
    #line hidden
    
    #line 25 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
    using System.Web.UI;
    
    #line default
    #line hidden
    
    #line 324 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System;
    
    #line default
    #line hidden
    
    #line 342 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.UI.HtmlControls;
    
    #line default
    #line hidden
    
    #line 333 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web;
    
    #line default
    #line hidden
    
    #line 329 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Configuration;
    
    #line default
    #line hidden
    
    #line 328 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.ComponentModel.DataAnnotations;
    
    #line default
    #line hidden
    
    #line 331 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Text;
    
    #line default
    #line hidden
    
    #line 338 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.Profile;
    
    #line default
    #line hidden
    
    #line 334 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.Caching;
    
    #line default
    #line hidden
    
    #line 325 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 25 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
    using System.Web.UI.WebControls.WebParts;
    
    #line default
    #line hidden
    
    #line 25 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
    using System.Web.UI.WebControls.Expressions;
    
    #line default
    #line hidden
    
    #line 327 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Collections.Specialized;
    
    #line default
    #line hidden
    
    #line 336 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.SessionState;
    
    #line default
    #line hidden
    
    #line 25 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
    using System.Web.DynamicData;
    
    #line default
    #line hidden
    
    
    [System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
    public class api_menu_aspx : global::Api_Menu, System.Web.IHttpHandler {
        
        private static System.Reflection.MethodInfo @__PageInspector_SetTraceDataMethod = global::ASP.api_menu_aspx.@__PageInspector_LoadHelper("SetTraceData");
        
        private static bool @__initialized;
        
        private static object @__fileDependencies;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public api_menu_aspx() {
            string[] dependencies;
            
            #line 912304 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx.cs"
            ((global::System.Web.UI.Page)(this)).AppRelativeVirtualPath = "~/Api/Menu.aspx";
            
            #line default
            #line hidden
            if ((global::ASP.api_menu_aspx.@__initialized == false)) {
                dependencies = new string[2];
                dependencies[0] = "~/Api/Menu.aspx";
                dependencies[1] = "~/Api/Menu.aspx.cs";
                global::ASP.api_menu_aspx.@__fileDependencies = this.GetWrappedFileDependencies(dependencies);
                global::ASP.api_menu_aspx.@__initialized = true;
            }
            this.Server.ScriptTimeout = 30000000;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control2() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n\r\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3" +
                    ".org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n\r\n<html xmlns=\"http://www.w3.org/1" +
                    "999/xhtml\">\r\n");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        92,
                        174,
                        true});
            return @__ctrl;
        }
        
        private static System.Reflection.MethodInfo @__PageInspector_LoadHelper(string helperName) {
            System.Type helperClass = System.Type.GetType("Microsoft.WebTools.BrowserLink.Runtime.WebForms.TraceHelpers, Microsoft.WebTools." +
                    "BrowserLink.Tracing, Version=16.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f1" +
                    "1d50a3a", false, false);
            if ((helperClass != null)) {
                return helperClass.GetMethod(helperName);
            }
            return null;
        }
        
        private void @__PageInspector_SetTraceData(object[] parameters) {
            if ((global::ASP.api_menu_aspx.@__PageInspector_SetTraceDataMethod != null)) {
                global::ASP.api_menu_aspx.@__PageInspector_SetTraceDataMethod.Invoke(null, parameters);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlTitle @__BuildControl__control4() {
            global::System.Web.UI.HtmlControls.HtmlTitle @__ctrl;
            
            #line 7 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlTitle();
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        293,
                        15,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control5() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n    <style type=\"text/css\">\r\n\ta\r\n\t{\r\n\t\ttext-decoration:none;\r\n\t}\r\n    a:hover\r\n" +
                    "    {\r\n    \ttext-decoration:underline;\r\n    }\r\n    a:visited\r\n    {\r\n    \t\r\n    " +
                    "\tcolor:Blue;\r\n    }\r\n    </style>\r\n");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        308,
                        196,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlHead @__BuildControl__control3() {
            global::System.Web.UI.HtmlControls.HtmlHead @__ctrl;
            
            #line 6 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlHead("head");
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlTitle @__ctrl1;
            
            #line 6 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__ctrl1 = this.@__BuildControl__control4();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 6 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl2;
            
            #line 6 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__ctrl2 = this.@__BuildControl__control5();
            
            #line default
            #line hidden
            
            #line 6 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        266,
                        245,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control6() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n<body style=\"padding:10px;font-size:14pt;\">\r\n    \t");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        511,
                        52,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control8() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("&raquo; Bind Profiler");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        640,
                        21,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.HyperLink @__BuildControl__control7() {
            global::System.Web.UI.WebControls.HyperLink @__ctrl;
            
            #line 25 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.HyperLink();
            
            #line default
            #line hidden
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 25 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__ctrl.NavigateUrl = "~/Api/Bind.aspx";
            
            #line default
            #line hidden
            
            #line 25 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__ctrl.Target = "content";
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 25 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__ctrl1 = this.@__BuildControl__control8();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 25 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        563,
                        114,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control9() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n    \t<br />\r\n    \t");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        677,
                        20,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control11() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("&raquo; View Trace");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        776,
                        18,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.HyperLink @__BuildControl__control10() {
            global::System.Web.UI.WebControls.HyperLink @__ctrl;
            
            #line 27 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.HyperLink();
            
            #line default
            #line hidden
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 27 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__ctrl.NavigateUrl = "~/Api/Trace.aspx";
            
            #line default
            #line hidden
            
            #line 27 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__ctrl.Target = "content";
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 27 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__ctrl1 = this.@__BuildControl__control11();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 27 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        697,
                        113,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control12() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n    \t<br />\r\n    \t");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        810,
                        20,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control14() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("&raquo; View Cache");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        911,
                        18,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.HyperLink @__BuildControl__control13() {
            global::System.Web.UI.WebControls.HyperLink @__ctrl;
            
            #line 29 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.HyperLink();
            
            #line default
            #line hidden
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 29 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__ctrl.NavigateUrl = "~/Api/Cache.aspx";
            
            #line default
            #line hidden
            
            #line 29 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__ctrl.Target = "cacheView";
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 29 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__ctrl1 = this.@__BuildControl__control14();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 29 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        830,
                        115,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control15() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n    \t\r\n    \t<br />\r\n    \t");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        945,
                        27,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control17() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("&raquo; View Code");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1052,
                        17,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.HyperLink @__BuildControl__control16() {
            global::System.Web.UI.WebControls.HyperLink @__ctrl;
            
            #line 32 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.HyperLink();
            
            #line default
            #line hidden
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 32 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__ctrl.NavigateUrl = "~/Api/Logger.aspx";
            
            #line default
            #line hidden
            
            #line 32 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__ctrl.Target = "content";
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 32 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__ctrl1 = this.@__BuildControl__control17();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 32 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        972,
                        113,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control18() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n    \t\r\n    \t<br />\r\n    \t");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1085,
                        27,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control20() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("&raquo; Adapters");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1196,
                        16,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.HyperLink @__BuildControl__control19() {
            global::System.Web.UI.WebControls.HyperLink @__ctrl;
            
            #line 35 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.HyperLink();
            
            #line default
            #line hidden
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 35 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__ctrl.NavigateUrl = "~/Api/Adapters.aspx";
            
            #line default
            #line hidden
            
            #line 35 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__ctrl.Target = "cacheView";
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 35 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__ctrl1 = this.@__BuildControl__control20();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 35 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1112,
                        116,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control21() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n    \t\r\n\r\n    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1228,
                        15,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control22() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n    <div>\r\n\t\t<br />\r\n\t\t");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1275,
                        25,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Button @__BuildControlButtonClearTrace() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            
            #line 41 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            
            #line default
            #line hidden
            this.ButtonClearTrace = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 41 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__ctrl.ID = "ButtonClearTrace";
            
            #line default
            #line hidden
            
            #line 41 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__ctrl.Text = "Clear Trace";
            
            #line default
            #line hidden
            
            #line 41 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__ctrl.Click += new System.EventHandler(this.ButtonClearTrace_Click);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1300,
                        108,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control23() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n\t\t<br />\r\n\t\t");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1408,
                        14,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Button @__BuildControlButtonClearCaches() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            
            #line 44 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            
            #line default
            #line hidden
            this.ButtonClearCaches = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 44 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__ctrl.ID = "ButtonClearCaches";
            
            #line default
            #line hidden
            
            #line 44 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__ctrl.Text = "Clear Caches";
            
            #line default
            #line hidden
            
            #line 44 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__ctrl.Click += new System.EventHandler(this.ButtonClearCaches_Click);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1422,
                        111,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control24() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n\t\t<br />\r\n\t\t");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1533,
                        14,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.CheckBox @__BuildControlCheckPaused() {
            global::System.Web.UI.WebControls.CheckBox @__ctrl;
            
            #line 47 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.CheckBox();
            
            #line default
            #line hidden
            this.CheckPaused = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 47 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__ctrl.ID = "CheckPaused";
            
            #line default
            #line hidden
            
            #line 47 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__ctrl.AutoPostBack = true;
            
            #line default
            #line hidden
            
            #line 47 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__ctrl.CheckedChanged += new System.EventHandler(this.CheckPaused_CheckedChanged);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1547,
                        119,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control25() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl(" \r\n\t\t");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1666,
                        5,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Label @__BuildControlLabel1() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 49 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            this.Label1 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 49 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__ctrl.AssociatedControlID = "CheckPaused";
            
            #line default
            #line hidden
            
            #line 49 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__ctrl.ID = "Label1";
            
            #line default
            #line hidden
            
            #line 49 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__ctrl.Text = "Paused";
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1671,
                        98,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control26() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl(" \r\n    </div>\r\n    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1769,
                        19,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlForm @__BuildControlform1() {
            global::System.Web.UI.HtmlControls.HtmlForm @__ctrl;
            
            #line 38 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlForm();
            
            #line default
            #line hidden
            this.form1 = @__ctrl;
            
            #line 38 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__ctrl.ID = "form1";
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 38 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__ctrl1 = this.@__BuildControl__control22();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 38 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Button @__ctrl2;
            
            #line 38 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__ctrl2 = this.@__BuildControlButtonClearTrace();
            
            #line default
            #line hidden
            
            #line 38 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl3;
            
            #line 38 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__ctrl3 = this.@__BuildControl__control23();
            
            #line default
            #line hidden
            
            #line 38 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Button @__ctrl4;
            
            #line 38 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__ctrl4 = this.@__BuildControlButtonClearCaches();
            
            #line default
            #line hidden
            
            #line 38 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl5;
            
            #line 38 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__ctrl5 = this.@__BuildControl__control24();
            
            #line default
            #line hidden
            
            #line 38 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.CheckBox @__ctrl6;
            
            #line 38 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__ctrl6 = this.@__BuildControlCheckPaused();
            
            #line default
            #line hidden
            
            #line 38 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__parser.AddParsedSubObject(@__ctrl6);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl7;
            
            #line 38 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__ctrl7 = this.@__BuildControl__control25();
            
            #line default
            #line hidden
            
            #line 38 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__parser.AddParsedSubObject(@__ctrl7);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Label @__ctrl8;
            
            #line 38 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__ctrl8 = this.@__BuildControlLabel1();
            
            #line default
            #line hidden
            
            #line 38 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__parser.AddParsedSubObject(@__ctrl8);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl9;
            
            #line 38 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__ctrl9 = this.@__BuildControl__control26();
            
            #line default
            #line hidden
            
            #line 38 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__parser.AddParsedSubObject(@__ctrl9);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1243,
                        552,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control27() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n</body>\r\n</html>\r\n");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1795,
                        20,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlTree(api_menu_aspx @__ctrl) {
            
            #line 1 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            this.InitializeCulture();
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 1 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__ctrl1 = this.@__BuildControl__control2();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlHead @__ctrl2;
            
            #line 1 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__ctrl2 = this.@__BuildControl__control3();
            
            #line default
            #line hidden
            
            #line 1 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl3;
            
            #line 1 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__ctrl3 = this.@__BuildControl__control6();
            
            #line default
            #line hidden
            
            #line 1 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.HyperLink @__ctrl4;
            
            #line 1 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__ctrl4 = this.@__BuildControl__control7();
            
            #line default
            #line hidden
            
            #line 1 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl5;
            
            #line 1 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__ctrl5 = this.@__BuildControl__control9();
            
            #line default
            #line hidden
            
            #line 1 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.HyperLink @__ctrl6;
            
            #line 1 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__ctrl6 = this.@__BuildControl__control10();
            
            #line default
            #line hidden
            
            #line 1 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__parser.AddParsedSubObject(@__ctrl6);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl7;
            
            #line 1 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__ctrl7 = this.@__BuildControl__control12();
            
            #line default
            #line hidden
            
            #line 1 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__parser.AddParsedSubObject(@__ctrl7);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.HyperLink @__ctrl8;
            
            #line 1 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__ctrl8 = this.@__BuildControl__control13();
            
            #line default
            #line hidden
            
            #line 1 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__parser.AddParsedSubObject(@__ctrl8);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl9;
            
            #line 1 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__ctrl9 = this.@__BuildControl__control15();
            
            #line default
            #line hidden
            
            #line 1 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__parser.AddParsedSubObject(@__ctrl9);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.HyperLink @__ctrl10;
            
            #line 1 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__ctrl10 = this.@__BuildControl__control16();
            
            #line default
            #line hidden
            
            #line 1 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__parser.AddParsedSubObject(@__ctrl10);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl11;
            
            #line 1 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__ctrl11 = this.@__BuildControl__control18();
            
            #line default
            #line hidden
            
            #line 1 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__parser.AddParsedSubObject(@__ctrl11);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.HyperLink @__ctrl12;
            
            #line 1 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__ctrl12 = this.@__BuildControl__control19();
            
            #line default
            #line hidden
            
            #line 1 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__parser.AddParsedSubObject(@__ctrl12);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl13;
            
            #line 1 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__ctrl13 = this.@__BuildControl__control21();
            
            #line default
            #line hidden
            
            #line 1 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__parser.AddParsedSubObject(@__ctrl13);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlForm @__ctrl14;
            
            #line 1 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__ctrl14 = this.@__BuildControlform1();
            
            #line default
            #line hidden
            
            #line 1 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__parser.AddParsedSubObject(@__ctrl14);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl15;
            
            #line 1 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__ctrl15 = this.@__BuildControl__control27();
            
            #line default
            #line hidden
            
            #line 1 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx"
            @__parser.AddParsedSubObject(@__ctrl15);
            
            #line default
            #line hidden
        }
        
        
        #line 912304 "C:\Users\jknauf\Documents\GitHub\AcumaticaTest\AcumaticaTest\Api\Menu.aspx.cs"
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void FrameworkInitialize() {
            this.StyleSheetTheme = "Default";
            base.FrameworkInitialize();
            this.@__BuildControlTree(this);
            this.AddWrappedFileDependencies(global::ASP.api_menu_aspx.@__fileDependencies);
            this.Request.ValidateInput();
        }
        
        #line default
        #line hidden
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override int GetTypeHashCode() {
            return -880174391;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override void ProcessRequest(System.Web.HttpContext context) {
            base.ProcessRequest(context);
        }
    }
}
