//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.CodeDom.Compiler.GeneratedCodeAttribute("ASP.NET", "4.0.30319.42000")]
[assembly: System.Security.SecurityRulesAttribute(System.Security.SecurityRuleSet.Level2)]
[assembly: System.Runtime.Versioning.TargetFrameworkAttribute(".NETFramework,Version=v4.8")]

namespace @__ASP {
    
    
    internal class FastObjectFactory_app_web_ujj35gqz {
        
        
        #line 1 "c:\\dummy.txt"

        #line default
        #line hidden
        
        
        private FastObjectFactory_app_web_ujj35gqz() {
        }
        
        static object Create_ASP_pages_fs_fs300230_aspx() {
            return new ASP.pages_fs_fs300230_aspx();
        }
        
        static object Create_ASP_pages_fs_fs300800_aspx() {
            return new ASP.pages_fs_fs300800_aspx();
        }
        
        static object Create_ASP_pages_fs_fs500600_aspx() {
            return new ASP.pages_fs_fs500600_aspx();
        }
        
        static object Create_ASP_pages_fs_fs404050_aspx() {
            return new ASP.pages_fs_fs404050_aspx();
        }
    }
}
