//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.CodeDom.Compiler.GeneratedCodeAttribute("ASP.NET", "4.0.30319.42000")]
[assembly: System.Security.SecurityRulesAttribute(System.Security.SecurityRuleSet.Level2)]
[assembly: System.Runtime.Versioning.TargetFrameworkAttribute(".NETFramework,Version=v4.8")]

namespace @__ASP {
    
    
    internal class FastObjectFactory_app_web_exhdcvy5 {
        
        
        #line 1 "c:\\dummy.txt"

        #line default
        #line hidden
        
        
        private FastObjectFactory_app_web_exhdcvy5() {
        }
        
        static object Create_ASP_pages_cr_co409000_aspx() {
            return new ASP.pages_cr_co409000_aspx();
        }
        
        static object Create_ASP_pages_cr_cr509010_aspx() {
            return new ASP.pages_cr_cr509010_aspx();
        }
        
        static object Create_ASP_pages_cr_cr306000_aspx() {
            return new ASP.pages_cr_cr306000_aspx();
        }
        
        static object Create_ASP_pages_cr_cr507000_aspx() {
            return new ASP.pages_cr_cr507000_aspx();
        }
        
        static object Create_ASP_pages_cr_cr305010_aspx() {
            return new ASP.pages_cr_cr305010_aspx();
        }
        
        static object Create_ASP_pages_cr_ou201000_aspx() {
            return new ASP.pages_cr_ou201000_aspx();
        }
    }
}
