//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.CodeDom.Compiler.GeneratedCodeAttribute("ASP.NET", "4.0.30319.42000")]
[assembly: System.Security.SecurityRulesAttribute(System.Security.SecurityRuleSet.Level2)]
[assembly: System.Runtime.Versioning.TargetFrameworkAttribute(".NETFramework,Version=v4.8")]

namespace @__ASP {
    
    
    internal class FastObjectFactory_app_web_xzemsoj5 {
        
        
        #line 1 "c:\\dummy.txt"

        #line default
        #line hidden
        
        
        private FastObjectFactory_app_web_xzemsoj5() {
        }
        
        static object Create_ASP_pages_tx_tx503500_aspx() {
            return new ASP.pages_tx_tx503500_aspx();
        }
        
        static object Create_ASP_pages_tx_tx207000_aspx() {
            return new ASP.pages_tx_tx207000_aspx();
        }
        
        static object Create_ASP_pages_tx_tx401000_aspx() {
            return new ASP.pages_tx_tx401000_aspx();
        }
        
        static object Create_ASP_pages_tx_tx205200_aspx() {
            return new ASP.pages_tx_tx205200_aspx();
        }
        
        static object Create_ASP_pages_tx_tx301000_aspx() {
            return new ASP.pages_tx_tx301000_aspx();
        }
        
        static object Create_ASP_pages_tx_tx209000_aspx() {
            return new ASP.pages_tx_tx209000_aspx();
        }
        
        static object Create_ASP_pages_tx_tx303000_aspx() {
            return new ASP.pages_tx_tx303000_aspx();
        }
    }
}
