//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.CodeDom.Compiler.GeneratedCodeAttribute("ASP.NET", "4.0.30319.42000")]
[assembly: System.Security.SecurityRulesAttribute(System.Security.SecurityRuleSet.Level2)]
[assembly: System.Runtime.Versioning.TargetFrameworkAttribute(".NETFramework,Version=v4.8")]

namespace @__ASP {
    
    
    internal class FastObjectFactory_app_web_q4gdw0ju {
        
        
        #line 1 "c:\\dummy.txt"

        #line default
        #line hidden
        
        
        private FastObjectFactory_app_web_q4gdw0ju() {
        }
        
        static object Create_ASP_pages_ar_ar202800_aspx() {
            return new ASP.pages_ar_ar202800_aspx();
        }
        
        static object Create_ASP_pages_ar_ar101000_aspx() {
            return new ASP.pages_ar_ar101000_aspx();
        }
        
        static object Create_ASP_pages_ar_ar205000_aspx() {
            return new ASP.pages_ar_ar205000_aspx();
        }
        
        static object Create_ASP_pages_ar_ar303010_aspx() {
            return new ASP.pages_ar_ar303010_aspx();
        }
        
        static object Create_ASP_pages_ar_ar202000_aspx() {
            return new ASP.pages_ar_ar202000_aspx();
        }
    }
}
